# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReCAPTHCHA():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reCAPTHCHA(self):
    self.driver.get("https://tobeto.com/kayit-ol")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("DASDASD")
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("ASDASDAS")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("john@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ASDFGH")
    self.driver.find_element(By.NAME, "passwordAgain").click()
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("ASDGFFG")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    element = self.driver.find_element(By.NAME, "contact")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "contact").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "membershipContrat").click()
    self.driver.find_element(By.NAME, "emailConfirmation").click()
    self.driver.find_element(By.NAME, "phoneConfirmation").click()
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 534 812 63 42")
    self.driver.switch_to.frame(6)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-yes").click()
  
