# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test_Test11111():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test11111(self):
    self.driver.get("https://tobeto.com/kayit-ol")
    self.driver.maximize_window()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("asdfasdasda")
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("asdasdasdas")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ahmetsuattanis@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("asdasdafa")
    self.driver.find_element(By.NAME, "passwordAgain").click()
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("afsdgfsdgsgs")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(4) > .text-muted").click()
    self.driver.find_element(By.NAME, "membershipContrat").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1)").click()
    self.driver.find_element(By.NAME, "phoneConfirmation").click()
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 534 812 63 42")
    self.driver.switch_to.frame(11)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(13)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    self.driver.find_element(By.ID, "recaptcha-verify-button").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(11)
    assert self.driver.find_element(By.CSS_SELECTOR, ".rc-anchor-error-msg").text == "Verification expired. Check the checkbox again."
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".rc-anchor-error-msg")))
  
