# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants.loginConstants import *
from selenium.webdriver.support import expected_conditions as ec

class TestWwwwwww():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def waitForElementVisible(self,locator,timeout=15):
      return WebDriverWait(self.driver,timeout).until(ec.visibility_of_element_located(locator))
  
  def waitForElementAvailableForIFrame(self,locator,timeout=10):
      return WebDriverWait(self.driver, timeout).until(ec.frame_to_be_available_and_switch_to_it(locator))
  
  def test_wwwwwww(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    self.waitForElementAvailableForIFrame((By.XPATH,"//iframe[@class='exw-launcher-frame animated bounce']"))
    self.waitForElementVisible((By.XPATH, "//*[@id='launcher']/div")).click()
    self.driver.switch_to.default_content()
    self.waitForElementAvailableForIFrame((By.XPATH,"//*[@id='exw-conversation-frame']"))
    messageBox=self.waitForElementVisible((By.XPATH,"//*[@id='exw-conversation-frame-body']/div/div/div/div[3]/form/textarea"))
    messageBox.send_keys("Selam")
    sendButton=self.waitForElementVisible((By.XPATH,"//*[@id='exw-conversation-frame-body']/div/div/div/div[3]/form/div/button"))
    sendButton.click()
    # sendButton = WebDriverWait(self.driver, timeout=10).until(ec.presence_of_element_located((By.XPATH, "//*[@id='exw-conversation-frame-body']/div/div/div/div[3]/form/div/button")))
    assert self.waitForElementVisible((By.XPATH, "//h4[contains(.,'Tobeto Yardım')]")).text=="Tobeto Yardım"
    assert "Merhabalar, Tobeto'ya hoş geldiniz." in self.waitForElementVisible((By.XPATH,"//div[@id='exw-messages']/div/div/div/div/div/div/p")).text
    self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[3]/div[2]/div[2]/input")).send_keys("Ahmet Suat")
    self.waitForElementVisible((By.CSS_SELECTOR,".exw-inline-response-input-container > svg")).click()
    #Normalde "Ahmet Suat" yazdığım için bana Memnun oldum Ahmet yazması gerekirken. ilk girdiğim "Selam" yazısı ile bana Memnun oldum Selam diyor.
    #Selam yazısını adım gibi alıp kullanıyor. Bug var burada
    assert "Memnun oldum" in self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[4]/div/div/div/div[1]/div/div")).text
    topicSelection=self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[4]/div/div/div/div[2]/div/div/div[1]"))
    topicSelection.click()
    assert "Tobeto; " in self.waitForElementVisible((By.XPATH,"//div[@class='exw-sender-response']/p[contains(text(),'Tobeto;')]")).text
    topicSelection2=self.waitForElementVisible((By.XPATH,"//div[@class='exw-reply'][contains(text(),'Eğitimlerimiz')]"))
    topicSelection2.click()
    assert "Aşağıdaki konu başlıkları için sana yardımcı olabilirim. 😊" in self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[8]/div/div/div/div[1]/div/div")).text
    topicSelection3=self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[8]/div/div/div/div[2]/div/div/div[1]"))
    topicSelection3.click()
    egitimler=["Dijital Gelişim","Profesyonel Gelişim","Yönetsel Gelişim"]
    #Bu kod, egitimler listesindeki her bir öğeyi self.waitForElementVisible(...).text stringinde arar. Tüm öğeler bulunursa True döner, aksi halde False döner. all fonksiyonu ise bu sonuçları birleştirir ve eğer tüm öğeler bulunursa True, aksi halde False döner.
    assert all(egitim in self.waitForElementVisible((By.XPATH,"//*[@id='exw-messages']/div[10]/div[1]/div/div")).text for egitim in egitimler)
    assert "Yardımcı olmamı istediğiniz başka bir konu var mı?" == self.waitForElementVisible((By.XPATH,"//div[@class='exw-message-text']/div[contains(text(),'Yardımcı')]")).text
    yesButton=self.waitForElementVisible((By.XPATH,"//div[@class='exw-replies']/div[contains(text(),'Evet')]"))
    noButton=self.waitForElementVisible((By.XPATH,"//div[@class='exw-replies']/div[contains(text(),'Hayır')]"))
    noButton.click()
    lastResponseMessage=self.waitForElementVisible((By.XPATH,"//div[@class='exw-sender-response']/p[contains(text(),'Sorun olursa her zaman burdayım')]"))
    assert "Sorun olursa her zaman burdayım" in lastResponseMessage.text






    
  
