# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.wait import WebDriverWait #ilgili driverı bekleten yapı
from selenium.webdriver.support import expected_conditions as ec #beklenen koşullar
from selenium.webdriver.common.action_chains import ActionChains 
import pytest
import openpyxl
from constants.RegisterConstants import *
import json 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLololo():
  def setup_method(self):
    self.driver=webdriver.Chrome()
    self.driver.maximize_window()
    
  def teardown_method(self):
    self.driver.quit()
  
  def test_lololo(self):
    self.driver.get("https://tobeto.com/kayit-ol")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("qweqweqwerq")
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("werwerwer")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("superboy_ahmet@hotmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("qw")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("qweqweqweqwe")
    self.driver.find_element(By.NAME, "passwordAgain").click()
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("qwqweqwe")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(4) > .text-muted").click()
    self.driver.find_element(By.NAME, "membershipContrat").click()
    self.driver.find_element(By.NAME, "emailConfirmation").click()
    self.driver.find_element(By.NAME, "phoneConfirmation").click()
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 534 812 63 42")
    self.waitForElementAvailableForIFrame((By.XPATH,"//iframe[starts-with(@name, 'a-') and starts-with(@src, 'https://www.google.com/recaptcha')]"))
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    sleep(62)
    error=self.driver.find_element(By.XPATH, "//div[@id='rc-anchor-container']//span[@class='rc-anchor-error-msg']")
    errorMessage=error.text
    assert errorMessage == "Verification expired. Check the checkbox again."
    
  

  def waitForElementAvailableForIFrame(self,locator,timeout=10):
      return WebDriverWait(self.driver, timeout).until(ec.frame_to_be_available_and_switch_to_it((locator)))
  
  def waitForElementVisible(self,locator,timeout=10):
      return WebDriverWait(self.driver,timeout).until(ec.visibility_of_element_located(locator))
    
  
